# Generated by Django 4.1.3 on 2022-12-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0002_board_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
